---
- name: Deploy app in new Namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: testing-my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /home/princeton/ansible-playbooks/kubeconfig-myapp
    - name: Deploy nginx app 
      kubernetes.core.k8s:
        src: /home/princeton/ansible-playbooks/nginx-config.yaml
        state: present
        kubeconfig: /home/princeton/ansible-playbooks/kubeconfig-myapp
        namespace: testing-my-app

